Add select menus
Lunarmagpie/hikari-flare pull request #21
Opened 2022-10-21 22:07 UTC by Lunarmagpie

Add select menus

2022-10-21 22:36 UTC, HyperGH requested changes

2022-10-21 22:36 UTC, HyperGH commented on flare/component.py
> +        select.add_to_container()
Chaining calls here would probably be better.

2022-10-22 00:25 UTC, Lunarmagpie commented on flare/component.py
> +        select.add_to_container()
I changed everything to default to None so this doesn't make sense anymore

2022-10-22 09:17 UTC, HyperGH approved these changes

2022-10-22 09:17 UTC, merged